#!/usr/bin/env python3
"""
Genesis Package Manager (genesis-pkg)

A package manager for Genesis programs, enabling developers to share
and reuse Avatars, Covenants, Domains, and complete Genesis modules.
"""

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Dict, List, Optional


class GenesisPackageManager:
    """Manages Genesis packages and dependencies."""
    
    def __init__(self):
        self.config_dir = Path.home() / ".genesis"
        self.packages_dir = self.config_dir / "packages"
        self.config_file = self.config_dir / "config.json"
        self._ensure_directories()
    
    def _ensure_directories(self):
        """Ensure package manager directories exist."""
        self.config_dir.mkdir(exist_ok=True)
        self.packages_dir.mkdir(exist_ok=True)
        
        if not self.config_file.exists():
            self.config_file.write_text(json.dumps({
                "registry": "https://genesishub.org/registry",
                "installed_packages": {}
            }, indent=2))
    
    def init_project(self, path: Optional[Path] = None):
        """Initialize a new Genesis project with package manifest."""
        project_dir = path or Path.cwd()
        manifest_path = project_dir / "genesis.manifest.json"
        
        if manifest_path.exists():
            print(f"❌ Project already initialized: {manifest_path}")
            return False
        
        # Create default manifest
        manifest = {
            "name": project_dir.name,
            "version": "0.1.0",
            "description": "A Genesis ASI project",
            "author": "",
            "license": "MIT",
            "genesis_version": ">=1.0.0",
            "dependencies": {},
            "dev_dependencies": {},
            "avatars": [],
            "domains": [],
            "covenants": []
        }
        
        manifest_path.write_text(json.dumps(manifest, indent=2))
        print(f"✅ Initialized Genesis project: {manifest_path}")
        
        # Create basic project structure
        (project_dir / "src").mkdir(exist_ok=True)
        (project_dir / "tests").mkdir(exist_ok=True)
        (project_dir / "avatars").mkdir(exist_ok=True)
        (project_dir / "domains").mkdir(exist_ok=True)
        
        # Create main.gen
        main_gen = project_dir / "src" / "main.gen"
        if not main_gen.exists():
            main_gen.write_text("""# Genesis Project
# Auto-generated by genesis-pkg init

Covenant "Core_Values" {
    Invariant: "Preserve human agency and wisdom"
    Threshold: 0.95
}

# Add your Pantheon, Domains, and logic here
""")
        
        print(f"✅ Created project structure in {project_dir}")
        return True
    
    def install_package(self, package_name: str, version: Optional[str] = None):
        """Install a Genesis package."""
        print(f"📦 Installing {package_name}...")
        
        # NOTE: This is a placeholder implementation for the package manager.
        # In a production implementation, this would:
        # 1. Connect to GenesisHub registry
        # 2. Fetch package metadata and verify integrity
        # 3. Download and install package files
        # 4. Update project manifest with dependencies
        # 5. Handle version conflicts and dependencies
        
        package_dir = self.packages_dir / package_name
        if package_dir.exists():
            print(f"✅ Package {package_name} already installed")
            return True
        
        # Simulate package installation (demo functionality)
        print("⚠️  Note: Package installation is simulated (GenesisHub registry not yet deployed)")
        package_dir.mkdir(exist_ok=True)
        (package_dir / "README.md").write_text(f"# {package_name}\n\nGenesis package")
        
        print(f"✅ Installed {package_name} (simulated)")
        return True
    
    def list_packages(self):
        """List installed packages."""
        packages = []
        if self.packages_dir.exists():
            packages = [p.name for p in self.packages_dir.iterdir() if p.is_dir()]
        
        if not packages:
            print("No packages installed")
            return
        
        print("📦 Installed Packages:")
        for pkg in sorted(packages):
            print(f"  - {pkg}")
    
    def search_packages(self, query: str):
        """Search for packages in the registry."""
        print(f"🔍 Searching for '{query}'...")
        print("⚠️  Note: Searching demo packages (GenesisHub registry not yet deployed)")
        
        # Mock search results for demonstration
        # In production, this would query the actual GenesisHub registry
        mock_results = [
            {"name": "avatar-templates", "description": "Common Avatar templates", "version": "1.0.0"},
            {"name": "ethics-covenants", "description": "Pre-built ethical Covenants", "version": "1.2.0"},
            {"name": "research-domains", "description": "Scientific research domains", "version": "0.9.0"},
        ]
        
        results = [r for r in mock_results if query.lower() in r["name"].lower()]
        
        if not results:
            print("No packages found")
            return
        
        print(f"\n📦 Found {len(results)} package(s) (demo data):")
        for pkg in results:
            print(f"  {pkg['name']} (v{pkg['version']}) - {pkg['description']}")
    
    def publish_package(self):
        """Publish current project as a package."""
        manifest_path = Path.cwd() / "genesis.manifest.json"
        
        if not manifest_path.exists():
            print("❌ No genesis.manifest.json found. Run 'genesis-pkg init' first.")
            return False
        
        manifest = json.loads(manifest_path.read_text())
        
        print(f"📦 Publishing {manifest['name']} v{manifest['version']}...")
        print("⚠️  Publishing to GenesisHub registry (not yet implemented)")
        print("✅ Package prepared for publication")
        
        return True


def main():
    """Main entry point for genesis-pkg CLI."""
    parser = argparse.ArgumentParser(
        description="Genesis Package Manager - Manage Genesis libraries and dependencies"
    )
    
    subparsers = parser.add_subparsers(dest="command", help="Available commands")
    
    # init command
    init_parser = subparsers.add_parser("init", help="Initialize a new Genesis project")
    init_parser.add_argument("path", nargs="?", help="Project path (default: current directory)")
    
    # install command
    install_parser = subparsers.add_parser("install", help="Install a package")
    install_parser.add_argument("package", nargs="?", help="Package name to install")
    install_parser.add_argument("--version", "-v", help="Specific version to install")
    
    # list command
    subparsers.add_parser("list", help="List installed packages")
    
    # search command
    search_parser = subparsers.add_parser("search", help="Search for packages")
    search_parser.add_argument("query", help="Search query")
    
    # publish command
    subparsers.add_parser("publish", help="Publish current project as a package")
    
    args = parser.parse_args()
    
    if not args.command:
        parser.print_help()
        return 1
    
    pkg_manager = GenesisPackageManager()
    
    if args.command == "init":
        path = Path(args.path) if args.path else None
        pkg_manager.init_project(path)
    
    elif args.command == "install":
        if args.package:
            pkg_manager.install_package(args.package, args.version)
        else:
            # Install from manifest
            manifest_path = Path.cwd() / "genesis.manifest.json"
            if manifest_path.exists():
                manifest = json.loads(manifest_path.read_text())
                for dep in manifest.get("dependencies", {}):
                    pkg_manager.install_package(dep)
            else:
                print("❌ No package specified and no genesis.manifest.json found")
    
    elif args.command == "list":
        pkg_manager.list_packages()
    
    elif args.command == "search":
        pkg_manager.search_packages(args.query)
    
    elif args.command == "publish":
        pkg_manager.publish_package()
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
