version: '1.0'
last_updated: '2026-02-11T23:57:31.125048Z'
entity_type: agent
metrics:
  total_invocations: 0
  success_rate: 0.0
  average_execution_time: 0.0
  resonance_scores:
    mean: 0.0
    min: 0.0
    max: 0.0
  task_categories: []
